import { NextPage } from "next";
import Head from "next/head";
import Router, { useRouter } from "next/router"
import { useContext, useState, useEffect } from "react";
import { UserRole } from "../../../assembly/main";
import { Role, roleOptions } from "../../../assembly/model";
import { NearContext } from "../../../context/NearContext";

const EditUserRole: NextPage = () => {
  const { contract, currentUser } = useContext(NearContext)
  const [role, setRole] = useState<number>(Role.Public)
  const [userRole, setUserRole] = useState<UserRole | null>(null)
  const [validationSummary, setValidationSummary] = useState<string>('')
  
  const router = useRouter()
  const { id } = router.query

  useEffect(() => {
    if (!contract) {
      setTimeout(() => {
        init()
      }, 5000)

      return
    }

    init()
  }, [])

  const init = async (): Promise<void> => {
    if (!contract) {
      return
    }
    
    if (!currentUser || currentUser.role !== Role.Admin) {
      Router.push('/')
    }

    const userRole: UserRole = await contract.getUserRole({ name: id })
    setUserRole(userRole)
    setRole(userRole.role)
  }

  const handleSubmit = async (): Promise<void> => {
    setValidationSummary('')

    if (!contract) {
      setValidationSummary('Contract is not available')
      return
    }

    // TODO: The PersistentUnorderedMap is not handling updates correctly.
    //await contract.setUser({ user: { username: userRole?.username, balance: '0' }, role })
    Router.push('/users/manage')
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Update Role for {userRole?.username}</h1>
        <select className="block px-3 py-2 mb-3 w-full" value={role} onChange={(e) => setRole(parseInt(e.target.value, 10))}>
          {roleOptions.map((key) => {
            return (
              <option value={key.value} key={key.value}>{key.label}</option>
            )
          })}
        </select>
        <button className="block px-3 py-2 mb-3 w-full" onClick={handleSubmit}>Add User</button>
      </main>
    </div>
  )
}

export default EditUserRole
