import { nanoid } from "nanoid"
import { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import Router, { useRouter } from "next/router"
import { useContext, useState, useEffect } from "react"
import { Field, Content } from "../../assembly/main"
import FieldsEditor from "../../components/FieldsEditor"
import { NearContext } from "../../context/NearContext"
import { get, getSet, put } from "../../services/db"

const EditContent: NextPage = () => {
  const { contract } = useContext(NearContext)
  const [name, setName] = useState('')
  const [fields, setFields] = useState<Field[]>([])
  const [currentContent, setCurrentContent] = useState<Content | null>(null)
  
  const router = useRouter()
  const { slug } = router.query

  useEffect(() => {
    if (!contract) {
      setTimeout(() => {
        init
      }
      , 5000)

      return
    }

    init()
  }, [])
  
  const init = () => {
    if (!contract) {
      return
    }

    contract.getContent({ slug }).then((ct: Content) => {
      setName(ct.name)
      const savedFields = ct.fields.map(f => {
        return get(`fields/${ct.slug}/${f.name}/fields/${ct.slug}/${f.name}`)
      })

      ct.fields = savedFields

      setFields(savedFields)
      setCurrentContent(ct)
    })
  }

  // TODO: Get update working right.
  const handleSubmit = (): void => {
    if (!contract) {
      return
    }
    
    const content: Content = { ...currentContent as Content, name, fields, updatedAt: new Date().toISOString() }
    fields.forEach(f => {
      put(`fields/${content.slug}/${f.name}`, f)
    })

    contract.setContent({ content }).then(() => {
      Router.push('/content')
    })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Create some content</h1>
        <label htmlFor="name">Name</label>
        <input className="block px-3 py-2 mb-3 w-full" type="text" value={name} onChange={(e) => setName(e.target.value)} />
        
        {fields && (
          <>
            <label htmlFor="fields">Fields</label>
            <FieldsEditor fields={fields} setFields={setFields} />
          </>
        )}
        
        <button className="block px-3 py-2 m-3 x-4 border border-green shadow-sm text-gray-light bg-green hover:bg-green focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green" onClick={handleSubmit}>Update</button>
        <Link href="/content">
          <a className="block">Back</a>
        </Link>
      </main>
    </div>
  )
}

export default EditContent
