import { useContext, useEffect, useState } from "react";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Router from "next/router";
import { Content } from '../../assembly/main'
import { NearContext } from "../../context/NearContext";
import { Role } from "../../assembly/model";

const Contents: NextPage = () => {
  const { contract, currentUser } = useContext(NearContext)
  const [content, setContent] = useState<Content[]>([])
  
  useEffect(() => {
    if (!contract) {
      setTimeout(() => {
        init
      }
      , 5000)

      return
    }

    init()
  }, [])
  
  const init = (): void => {
    if (!contract) {
      return
    }

    if (!currentUser || currentUser.role > Role.Editor) {
      Router.push('/')
    }

    contract.getContents().then((ct: Content[]) => {
      setContent(ct)
    })
  }

  const deleteContent = (ct: Content): void => {
    if (!contract) {
      return
    }

    contract.deleteContent({ content: ct }).then(() => {
      init()
    })
  }

  const editContent = (ct: Content): void => {
    if (!contract) {
      return
    }

    Router.push('/content/[slug]', `/content/${ct.slug}`)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Content Types</h1>
        {!contract && <div>Loading...</div>}
        {contract && !content.length && <button onClick={init}>Load</button>}
        <table>
          <thead>
            <tr>
              <th>Actions</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
          {contract && content && content.map((ct) => {
            return (
              <tr key={ct.name}>
                <td>
                  <button onClick={() => editContent(ct)}>Edit</button>
                  <button onClick={() => deleteContent(ct)}>Delete</button>
                </td>
                <td>{ct.name}</td>
              </tr>
            )
          })}
          </tbody>
        </table>
        <Link href="/content/new">
          <a>New</a>
        </Link>
      </main>
    </div>
  )
}

export default Contents
