import { NextPage } from "next";
import { useContext, useEffect, useState } from "react";
import { NearContext } from "../../context/NearContext";
import { Content } from '../../assembly/main'
import Head from "next/head";
import Link from "next/link";

const Contents: NextPage = () => {
  const { contract, currentUser, nearConfig, wallet, setCurrentUser } = useContext(NearContext)
  const [content, setContent] = useState<Content[]>([])
  
  useEffect(() => {
    if (!contract) {
      setTimeout(() => {
        init
      }
      , 5000)

      return
    }

    init()
  }, [])
  
  const init = () => {
    if (!contract) {
      return
    }

    contract.getContents().then((ct: Content[]) => {
      setContent(ct)
    })
  }

  const deleteContent = (ct: Content): void => {
    if (!contract) {
      return
    }

    contract.deleteContent({ name: ct.name }).then(() => {
      init()
    })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Content Types</h1>
        {!contract && <div>Loading...</div>}
        {contract && !content.length && <button onClick={init}>Load</button>}
        <table>
          <thead>
            <tr>
              <th>Actions</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
          {contract && content && content.map((ct) => {
            return (
              <tr key={ct.name}>
                <td><button onClick={() => deleteContent(ct)}>Delete</button></td>
                <td>{ct.name}</td>
              </tr>
            )
          })}
          </tbody>
        </table>
        <Link href="/content/new">
          <a>New</a>
        </Link>
      </main>
    </div>
  )
}

export default Contents
