import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useState } from 'react'
import { NearContext } from '../../context/NearContext'
//import styles from '../styles/Home.module.css'
import Router from 'next/router'
import { Fieldtype, fieldTypeOptions } from '../../assembly/model'

const NewField: NextPage = () => {
  const { contract, currentUser, nearConfig, wallet, setCurrentUser } = useContext(NearContext)
  const [fieldName, setFieldName] = useState('')
  const [fieldType, setFieldType] = useState(Fieldtype.String)

  const handleFieldTypeChange = (event: React.ChangeEvent<HTMLSelectElement>): void => {
    setFieldType(event.target.value as Fieldtype)
  }

  const handleSubmit = (): void => {
    if (!contract) {
      return
    }

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1></h1>

        <input className="block px-3 py-2 mb-3 w-full" type="text" value={fieldName} onChange={(e) => setFieldName(e.target.value)} />
        <select className="block px-3 py-2 mb-3 w-full" onChange={(e) => handleFieldTypeChange(e)}>
          {fieldTypeOptions.map((key) => {
            return (
              <option value={key.value} key={key.value}>{key.label}</option>
            )
          })}
        </select>
        <button className="px-3 py-2 m-3 x-4 border border-green shadow-sm text-gray-light bg-green hover:bg-green focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green" onClick={handleSubmit}>Create</button>
      </main>
    </div>
  )
}

export default NewField