import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import { NearContext } from '../../context/NearContext'
import { Role, roleOptions } from '../../assembly/model'
import { UserRole } from '../../assembly/main'
import Router from 'next/router'

const ManageUsers: NextPage = () => {
  const { contract } = useContext(NearContext)
  const [accountId, setAccountId] = useState('')
  const [role, setRole] = useState(Role.Public)
  const [users, setUsers] = useState<UserRole[]>([])

  useEffect(() => {
    if (!contract) {
      setTimeout(() => {
        init()
      }, 5000)

      return
    }

    init()
  }, [])

  const init = () => {
    if (!contract) {
      return
    }

    contract.getUsers().then((userRoles: UserRole[]) => {
      setUsers(userRoles)
    })
  }

  const handleSubmit = async () => {
    if (!contract) {
      return
    }

    // const user = await contract.getUser({ username: accountId })
    // if (user) {
    //   // need to set a message here to let the user know that the account already exists
    //   return
    // }
    console.log('role', role)

    await contract.setUser({ user: { accountId, balance: '0' }, role })
    Router.push('/users')
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Manage Users</h1>
        <a href="/">Back to dashboard</a>
        <table>
          <thead>
            <tr>
              <th>Account ID</th>
              <th>Role</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {users.map(user => (
              <tr key={user.username}>
                <td>{user.username}</td>
                <td>{roleOptions[user.role].value}</td>
                <td>
                  <button>Edit</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <label htmlFor="accountId">Account ID</label>
        <input className="block px-3 py-2 mb-3 w-full" type="text" value={accountId} onChange={(e) => setAccountId(e.target.value)} />
        <select className="block px-3 py-2 mb-3 w-full" value={role} onChange={(e) => setRole(e.target.value)}>
          {roleOptions.map((key) => {
            return (
              <option value={key.value} key={key.value}>{key.label}</option>
            )
          })}
        </select>
        <button className="block px-3 py-2 mb-3 w-full" onClick={handleSubmit}>Add User</button>
      </main>
    </div>
  )
}

export default ManageUsers
