import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import { NearContext } from '../../context/NearContext'
//import styles from '../styles/Home.module.css'
import Router from 'next/router'
import { Fieldtype, fieldTypeOptions } from '../../assembly/model'
import { ContentType } from '../../assembly/main'

const ContentTypes: NextPage = () => {
  const { contract, currentUser, nearConfig, wallet, setCurrentUser } = useContext(NearContext)
  const [contentType, setContentType] = useState<ContentType | null>()

  useEffect(() => {
    if (!contract) {
      return
    }

    contract.getContentType({ name: 'Date' }).then((ct) => {
      console.log('ct', ct)
      setContentType(ct)
    })
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Create a Content Type</h1>
        {contentType && (
          <p>{contentType.name}</p>
        )}
      </main>
    </div>
  )
}

export default ContentTypes
